---
excludes:
  scopes:
    - pattern: "lint"
      reason: "DEV_DEPENDENCY_OF"
      comment: "Packages for static code analysis only."
    - pattern: "test"
      reason: "TEST_DEPENDENCY_OF"
      comment: "Packages for testing only."
    - pattern: "nox"
      reason: "TEST_DEPENDENCY_OF"
      comment: "Packages for testing only."
    - pattern: "doc"
      reason: "DOCUMENTATION_DEPENDENCY_OF"
      comment: "Packages for building the documentation only."
    - pattern: "eval"
      reason: "DEV_DEPENDENCY_OF"
      comment: "Packages for quality evaluation only."
license_choices:
  repository_license_choices:
    - given: FTL OR GPL-2.0-or-later
      choice: FTL

resolutions:
  rule_violations:
    - message: ".*PyPI::pyinstrument:4\\.6\\.1.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/joerick/pyinstrument/blob/main/LICENSE"
    - message: ".*PyPI::httpcore:1\\.0\\.9.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/encode/httpcore/blob/1.0.9/LICENSE.md"
    - message: ".*PyPI::pandas:2\\.2\\.2.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/pandas-dev/pandas/blob/main/LICENSE"
    - message: ".*PyPI::fsspec:2024\\.6\\.1.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/fsspec/filesystem_spec/blob/master/LICENSE"
    - message: ".*PyPI::cycler:0\\.12\\.1.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/matplotlib/cycler/blob/main/LICENSE"
    - message: ".*PyPI::nvidia-cusparselt-cu12:0\\.6\\.3.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "NVIDIA proprietary license: https://developer.nvidia.com/cusparselt"
    - message: ".*PyPI::numpy:1\\.26\\.4.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/numpy/numpy/blob/main/LICENSE.txt"
    - message: ".*PyPI::pypdfium2:4\\.30\\.1.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD-3-Clause AND Apache-2.0: https://github.com/pypdfium2-team/pypdfium2/blob/main/LICENSE"
    - message: ".*PyPI::httpx:0\\.27\\.2.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/encode/httpx/blob/master/LICENSE.md"
    - message: ".*PyPI::pypdf:5\\.3\\.0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/py-pdf/pypdf/blob/main/LICENSE"
    - message: ".*PyPI::contourpy:1\\.3\\.0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/matplotlib/contourpy/blob/main/LICENSE"
    - message: ".*PyPI::scipy:1\\.14\\.1.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/scipy/scipy/blob/main/LICENSE.txt"
    - message: ".*PyPI::tiktoken:0\\.7\\.0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/openai/tiktoken/blob/main/LICENSE"
    - message: ".*PyPI::jinja2:3\\.1\\.6.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/pallets/jinja/blob/3.1.6/LICENSE.txt"
    - message: ".*PyPI::omegaconf:2\\.3\\.0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/omry/omegaconf/blob/main/LICENSE"
    - message: ".*PyPI::emoji:2\\.12\\.1.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/carpedm20/emoji/blob/main/LICENSE"
    - message: ".*PyPI::setuptools:80\\.7\\.1.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/pypa/setuptools/blob/main/LICENSE"
    - message: ".*PyPI::iopath:0\\.1\\.10.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/facebookresearch/iopath/blob/main/LICENSE"
    - message: ".*PyPI::networkx:3\\.3.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/networkx/networkx/blob/main/LICENSE.txt"
    - message: ".*PyPI::libmagic:1\\.0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "GPL-3.0-or-later: https://github.com/ahupp/python-magic/blob/master/LICENSE"
    - message: ".*PyPI::ndjson:0\\.3\\.1.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "GPL-3.0-only: https://github.com/rhgrant10/ndjson/blob/main/LICENSE"
    - message: ".*PyPI::nvidia-cusparse-cu12:12\\.5\\.4\\.2.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "NVIDIA proprietary license: https://developer.nvidia.com/cusparse"
    - message: ".*PyPI::docarray:0\\.39\\.1.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Apache-2.0 AND proprietary: https://github.com/docarray/docarray/blob/main/LICENSE"
    - message: ".*PyPI::nvidia-nccl-cu12:2\\.26\\.2.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "NVIDIA proprietary license: https://developer.nvidia.com/nccl"
    - message: ".*PyPI::nvidia-cusolver-cu12:11\\.7\\.1\\.2.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "NVIDIA proprietary license: https://developer.nvidia.com/cusolver"
    - message: ".*PyPI::nvidia-nvtx-cu12:12\\.6\\.77.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "NVIDIA proprietary license: https://developer.nvidia.com/nvtx"
    - message: ".*PyPI::nvidia-cudnn-cu12:9\\.5\\.1\\.17.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "NVIDIA proprietary license: https://developer.nvidia.com/cudnn"
    - message: ".*PyPI::nvidia-nvjitlink-cu12:12\\.6\\.85.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "NVIDIA proprietary license: https://developer.nvidia.com/cuda"
    - message: ".*PyPI::nvidia-curand-cu12:10\\.3\\.7\\.77.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "NVIDIA proprietary license: https://developer.nvidia.com/curand"
    - message: ".*PyPI::nvidia-cuda-nvrtc-cu12:12\\.6\\.77.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "NVIDIA proprietary license: https://developer.nvidia.com/cuda"
    - message: ".*PyPI::nvidia-cuda-cupti-cu12:12\\.6\\.80.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "NVIDIA proprietary license: https://developer.nvidia.com/cuda"
    - message: ".*PyPI::nvidia-cuda-runtime-cu12:12\\.6\\.77.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "NVIDIA proprietary license: https://developer.nvidia.com/cuda"
    - message: ".*PyPI::nvidia-cufft-cu12:11\\.3\\.0\\.4.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "NVIDIA proprietary license: https://developer.nvidia.com/cufft"
    - message: ".*PyPI::aiohappyeyeballs:2\\.4\\.0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "PSF-2.0 license: https://github.com/aio-libs/aiohappyeyeballs/blob/main/LICENSE"
    - message: ".*PyPI::nvidia-cufile-cu12:1\\.11\\.1\\.6.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "NVIDIA proprietary license: https://developer.nvidia.com/cufile"
    - message: ".*PyPI::nvidia-cublas-cu12:12\\.6\\.4\\.1.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "NVIDIA proprietary license: https://developer.nvidia.com/cublas"
    - message: ".*PyPI::kiwisolver:1\\.4\\.7.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/nucleic/kiwisolver/blob/main/LICENSE"
    - message: ".*PyPI::pdfminer-six:20231228.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT/X License: https://github.com/pdfminer/pdfminer.six/blob/master/LICENSE"
    - message: ".*PyPI::python-dateutil:2\\.9\\.0\\.post0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD License and Dual License: https://github.com/dateutil/dateutil/blob/master/LICENSE"
    - message: ".*PyPI::ninja:1\\.11\\.1\\.1.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Apache-2.0 License: https://github.com/ninja-build/ninja/blob/master/LICENSE"
